### ISSUE TITLE
Incorrect Carthage Installation Command in ReadMe

### ISSUE THREAD

**Issue by mattjankowiak** [particle-iot/particle-cloud-sdk-ios#1]
Greetings,

It looks like the Carthage Installation section of the readme has the wrong Carthage command.  It currently states to use:

`github "particle/particle-sdk-ios" "master"`

whereas is should probably be:

`github "spark/particle-sdk-ios" "master"`

Looks like just a little typo 😄 Let me know if I'm missing something obvious here, but the first command was failing for me (obvious reasons), and the second one here worked like a charm.

**Comment by xerisystems** [comment]
I'm completely new to all of this so I may not be correct but I had to use particle-iot in my Cartfile:

`github "particle-iot/particle-sdk-ios" "master"`

**Comment by RaimundasSakalauskas** [comment]
Readme is now simplified and content is being moved to https://docs.particle.io/reference/ios/. The latest certfile should read `github "particle-iot/particle-sdk-ios" ~> 0.8.1`
