### ISSUE TITLE
Max function argument size

### ISSUE THREAD

**Issue by mcgouganp** [particle-iot/particle-cloud-sdk-ios#10]
File particle-sdk-ios/ParticleSDK/SDK/ParticleDevice.m limits maximum function argument to 63. Particle documentation seems to indicate that the limit has been raised to 622 in Device Firmware and in backend cloud.

**Comment by RaimundasSakalauskas** [comment]
Thank you for reporting. You are correct. Will release patch addressing this later today.

**Comment by RaimundasSakalauskas** [comment]
This has been fixed: https://github.com/particle-iot/particle-sdk-ios/releases/tag/0.9.2
