### ISSUE TITLE
Pod dependency AFNetworking using deprecated UIWebView

### ISSUE THREAD

**Issue by jeremiahogutu** [particle-iot/particle-cloud-sdk-ios#21]
The particle cloud sdk is referencing AFNetworking pod (v3.2.1) which is using deprecated UIWebView. This has been fixed in version 4.0.0 which was released on March 29th. See reference issue on this https://github.com/AFNetworking/AFNetworking/pull/4439

Note from apple
![uiwebview](https://user-images.githubusercontent.com/28146531/78950241-1db35400-7a9c-11ea-91cb-0eb1d7521c84.png)

xcode search 
![AFNetworking](https://user-images.githubusercontent.com/28146531/78950408-aaf6a880-7a9c-11ea-8556-1ef0793b15bc.png)

**Comment by RaimundasSakalauskas** [comment]
This was fixed in 1.0.5 release. Thank you for reporting :). https://github.com/particle-iot/particle-cloud-sdk-ios/releases/tag/1.0.5
