### ISSUE TITLE
v0.8.0 and v0.8.1 won't build

### ISSUE THREAD

**Issue by mcgouganp** [particle-iot/particle-cloud-sdk-ios#6]
When building from scratch using a Cartfile of:
```
github "particle-iot/particle-sdk-ios" ~> 0.8.1
github "particle-iot/particle-setup-ios" ~> 0.9.0
```

results in:
```
$ carthage update
*** Fetching particle-sdk-ios
*** Fetching particle-setup-ios
*** Fetching AFNetworking
*** Fetching onepassword-extension
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Carthage/Checkouts/AFNetworking) but encountered: 

```

[Research](https://github.com/Carthage/Carthage/issues/1763) indicates that this means that the .gitmodules of particle-sdk-ios is possibly incorrect.

**Comment by mcgouganp** [comment]
Still happens with just a Cartfile of:
`github "particle-iot/particle-sdk-ios" ~> 0.8.1`

and running the recommended command (doh! RTFM):
```
$ carthage update --platform iOS --use-submodules --no-use-binaries
*** Fetching particle-sdk-ios
*** Fetching AFNetworking
Parse error: expected submodule commit SHA in output of task (ls-tree -z HEAD Carthage/Checkouts/AFNetworking) but encountered: 


```

**Comment by mcgouganp** [comment]
Interestingly the issue appeared to be with my *local* .gitmodules not the one in the repository.
Deleted it and committed the deletion to local git and problem was fixed.
Apologies for the noise.

**Comment by RaimundasSakalauskas** [comment]
Submodules give me hard time too. If anyone else experience the issue, please let me know, I will do a realease with no submodule specs (for me this has higher success chance).
